# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "azure_mqtt_ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { version = "1", default-features = false }
either = { version = "1.6", default-features = false }
log = {version = "0.4", default-features = false }
parking_lot = { version = "0.12", default-features = false }
thiserror = { version = "2", default-features = false }
tokio = { version = "1.38", default-features = false, features = ["io-util", "macros", "net", "rt", "sync", "time"] }

azure_mqtt = { path = ".." }


[lib]
crate-type = ["cdylib"]
