[package]
name = "io"
version = "0.1.0"
authors = ["Azure IoT Operations Devs"]
license = "MIT"
edition = "2024"


[dependencies]
tokio = { workspace = true, features = ["io-util", "net"] }

buffer-pool = { path = "../buffer-pool" }
mqtt-proto = { path = "../mqtt-proto" }


[features]
tests = []


[lints]
workspace = true
