[package]
name = "io"
version = "0.1.0"
authors = ["Azure IoT Operations Devs"]
license = "MIT"
edition = "2024"


[dependencies]
nix = { workspace = true, features = ["net", "process", "socket", "zerocopy"] }
openssl = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net"] }
tokio-openssl = { workspace = true }

buffer-pool = { path = "../buffer-pool" }
mqtt-proto = { path = "../mqtt-proto" }
opensslext = { path = "../opensslext" }


[dev-dependencies]
matches = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }


[features]
tests = []


[lints]
workspace = true
