name: 'CI'

on:
- 'pull_request'
- 'push'

permissions:
  contents: read

jobs:
  check:
    runs-on: 'ubuntu-24.04'

    steps:
    - uses: 'actions/checkout@v4'
    - name: Install build deps
      run: |
        ./ci/install-build-deps.sh
    - name: Check
      run:
        make -j check

  test:
    runs-on: 'ubuntu-24.04'

    steps:
    - uses: 'actions/checkout@v4'
    - name: Install build deps
      run: |
        ./ci/install-build-deps.sh
    - name: Test
      run:
        make -j test
